zuul:
    sslHostnameValidationEnabled: false
    ignoredServices: "*"
    routes:
        customer-services:
          path: /user/**
          serviceId: NETFLIX-STREAMING-USER
        friend-services:
          path: /device/**
          serviceId: NETFLIX-STREAMING-DEVICE
        plan-services:
          path: /plan/**
          serviceId: NETFLIX-STREAMING-PLAN
    host:
      time-to-live: -1
      connect-timeout-millis: 5000
      max-per-route-connections: 10000
      max-total-connections: 5000
      socket-timeout-millis: 60000
    semaphore:
      max-semaphores: 500  
            